### PR TITLE
plug gush

### PR DESCRIPTION
**Pull request by cordoval**
| Q | A |
| --- | --- |
| Bug Fix? | no |
| New Feature? | no |
| BC Breaks? | no |
| Deprecations? | no |
| Tests Pass? | no |
| Fixed Tickets |  |
| License | MIT |

 Sent using [Gush](https://github.com/gushphp/gush)

### CODE REVIEW

**Comment by ericvanjohnson** [comment]
Don't we need to add Gush to the composer.json file as well?

**Comment by ericvanjohnson** [comment]
Oh I see you install globally

**Comment by ericvanjohnson** [comment]
Can you just add a quick snippet to the Projects ReadMe. I will even write it for you.

## Gush

This project can be managed with [Gush](https://github.com/gushphp/gush). To install Gush Globally run;

`composer global require gushphp/gush=dev-master`

For more information check out the [Gush](https://github.com/gushphp/gush) repo.

**Comment by cordoval** [comment]
:+1: do you want me to send the PR? or you have it? nvm i will send the PR

**Comment by ericvanjohnson** [comment]
Just add it to this Pull Request. I think Github updates it auto-magically

**Comment by cryptiklemur** [comment]
can also be installed as a phar `curl -sS http://gushphp.org/installer | php`

**Comment by cordoval** [comment]
done @shocm 

:dancer:

**Pull request merged**
