### PR TITLE
Registration and Login Workflow

### PR DESCRIPTION
**Pull request by jasonmccallister**
Completing two workflows, added base template structure. Will continue with design and send new changes.

### CODE REVIEW

**Comment by cryptiklemur** [comment]
@sdphp/owners Are we following any PSR Standards? I'd suggest following all of them

**Comment by ericvanjohnson** [comment]
@themccallister We want to keep `app/config/database.php` in the `.gitignore` file because we don't want people accidently submitting their database credentials. 

Also, I created a development branch, can you send your pull request there. That will allow us to test it out before merging it into the master branch. Will probably follow this workflow until we get some good test set up that we can run against the application.   

@aequasi I think that following PSR Standards is a reasonable suggestion, especially if you are volunteering to help police it. :-)

**Comment by johncongdon** [comment]
@shocm I made the default branch development so future PR's will come to that unless changed on their end.

You can still test on the dev branch, you just have to use command line, not GitHub's big green merge button. ;-)

**Comment by jasonmccallister** [comment]
Please feel free to point and laugh at any horrible code I may have pushed... I'm looking up PSR standards and trying to ensure I follow those.

Closing and starting the PR on development branch.

**Pull request closed without merging**
